export type PropertyType = "apartment" | "house" | "villa" | "plot" | "commercial" | "pg";
export type TransactionType = "sale" | "rent" | "lease";
export type PriceUnit = "total" | "per_sqft" | "per_month";
export type Furnishing = "unfurnished" | "semi" | "fully";
export type ListingStatus = "draft" | "active" | "sold" | "rented" | "archived";

export interface Listing {
  id: string;
  organization_id: string;
  created_by: string;
  title: string;
  description: string | null;
  property_type: PropertyType;
  transaction_type: TransactionType;
  price: number;
  price_unit: PriceUnit;
  address: string | null;
  locality: string | null;
  city: string;
  state: string;
  pincode: string | null;
  latitude: number | null;
  longitude: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  area_sqft: number | null;
  carpet_area_sqft: number | null;
  floor_number: number | null;
  total_floors: number | null;
  furnishing: Furnishing | null;
  facing: string | null;
  age_years: number | null;
  parking: number;
  amenities: string[];
  images: string[];
  floor_plan_url: string | null;
  virtual_tour_url: string | null;
  ai_description: string | null;
  ai_social_post: string | null;
  ai_seo_title: string | null;
  ai_seo_description: string | null;
  ai_highlights: string[];
  status: ListingStatus;
  views_count: number;
  inquiries_count: number;
  published_platforms: string[];
  external_urls: Record<string, string>;
  created_at: string;
  updated_at: string;
}
