import Link from "next/link";
import {
  Building2,
  Sparkles,
  ArrowRight,
  FileText,
  Users,
  Trophy,
  Brain,
  MessageSquareText,
  Building,
  CalendarClock,
  TrendingUp,
  Check,
  KanbanSquare,
  MessageCircle,
  Heart,
  Zap,
  Globe,
  LayoutDashboard,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { PricingSection } from "@/components/landing/pricing-toggle";
import { FaqAccordion } from "@/components/landing/faq-accordion";
import { createClient } from "@/lib/supabase/server";

/* ================================================================== */
/*  DATA                                                               */
/* ================================================================== */

const INTEGRATIONS = [
  "Supabase",
  "Razorpay",
  "Twilio",
  "Next.js",
  "Vercel",
];

const STEPS = [
  {
    number: "01",
    icon: FileText,
    title: "Create AI Listings",
    description:
      "Enter basic property details and let AI generate professional titles, descriptions, social posts, and SEO keywords in seconds.",
  },
  {
    number: "02",
    icon: Users,
    title: "Manage & Score Leads",
    description:
      "Import leads from 99acres, MagicBricks, or CSV. AI scores each lead 0–100 and prioritises your follow-ups.",
  },
  {
    number: "03",
    icon: Trophy,
    title: "Close Deals Faster",
    description:
      "WhatsApp smart replies, AI follow-up suggestions, and pipeline analytics to convert more leads into happy homeowners.",
  },
];

const AI_FEATURES = [
  {
    icon: Sparkles,
    title: "AI Listing Generator",
    description:
      "Professional titles, vivid descriptions, social media posts, and SEO tags — generated by AI in seconds.",
    accent: "bg-primary-50 text-primary-600",
  },
  {
    icon: Users,
    title: "Smart CRM",
    description:
      "AI-powered lead scoring, drag-and-drop pipeline, activity timeline, and bulk CSV import from any portal.",
    accent: "bg-info-50 text-info-600",
  },
  {
    icon: MessageSquareText,
    title: "AI Smart Reply",
    description:
      "Contextual WhatsApp reply suggestions for every incoming message. One tap to send — zero wait time.",
    accent: "bg-success-50 text-success-600",
  },
  {
    icon: Building,
    title: "AI Property Matching",
    description:
      "Automatically match incoming leads to your best-fit listings based on budget, location, and preferences.",
    accent: "bg-warning-50 text-warning-600",
  },
  {
    icon: CalendarClock,
    title: "AI Follow-Up Engine",
    description:
      "Optimal time, channel, and talking points for each follow-up — so you never miss the right moment.",
    accent: "bg-purple-50 text-purple-600",
  },
  {
    icon: TrendingUp,
    title: "AI Listing Optimizer",
    description:
      "Analyses existing listings and suggests improvements to titles, descriptions, and pricing to boost leads.",
    accent: "bg-cyan-50 text-cyan-600",
  },
];

const AI_EXAMPLES = [
  {
    icon: Sparkles,
    title: "Listing Generator",
    example:
      '"Luxurious 3BHK in Bandra West with sea-facing balcony, modular kitchen, and 24/7 security. Premium amenities include infinity pool, gymnasium..."',
    accent: "text-primary-400 bg-primary-500/10",
  },
  {
    icon: Brain,
    title: "Lead Scoring",
    example:
      "Score: 87/100 — Hot Lead\nBudget match: High\nResponse time: Fast\nSource: Referral (premium)",
    accent: "text-info-400 bg-info-500/10",
  },
  {
    icon: MessageSquareText,
    title: "Smart Reply",
    example:
      '1. "Yes, the flat is available for viewing this weekend..."\n2. "I can schedule a visit for Saturday at 11 AM..."\n3. "The asking price is negotiable for serious buyers..."',
    accent: "text-green-400 bg-green-500/10",
  },
  {
    icon: Building,
    title: "Property Matching",
    example:
      "3 matching listings found for Rajesh's requirements:\n• Sea View 3BHK Andheri — 92% match\n• Premium 3BHK Goregaon — 78% match",
    accent: "text-yellow-400 bg-yellow-500/10",
  },
  {
    icon: CalendarClock,
    title: "Follow-Up Engine",
    example:
      "Call Priya tomorrow at 11 AM about the Andheri flat — she viewed it twice this week. Mention the new price drop.",
    accent: "text-purple-400 bg-purple-500/10",
  },
  {
    icon: TrendingUp,
    title: "Listing Optimizer",
    example:
      "Score: 6/10 — 3 suggestions:\n• Add carpet area to title (+28% views)\n• Mention nearby metro station\n• Update price to market rate",
    accent: "text-cyan-400 bg-cyan-500/10",
  },
];

const CRM_PIPELINE_FEATURES = [
  "Drag-and-drop lead management",
  "7-stage customizable pipeline",
  "Activity timeline for every lead",
  "CSV import from 99acres & MagicBricks",
  "AI-powered lead scoring & matching",
];

const WHATSAPP_FEATURES = [
  "Two-way WhatsApp messaging",
  "Pre-built & custom message templates",
  "AI smart reply suggestions",
  "Auto-logged to lead activity",
  "Browser & email notifications",
];

const FAQ_ITEMS = [
  {
    question: "What is PropGenius AI?",
    answer:
      "PropGenius AI is an all-in-one real estate platform built for Indian agents and agencies. It combines AI-powered listing generation, smart CRM with lead scoring, WhatsApp integration, and analytics dashboard to help you close more deals faster.",
  },
  {
    question: "How does the AI listing generator work?",
    answer:
      "Simply enter your property details — type, location, price, bedrooms, amenities — and our AI generates a professional title, detailed description, social media post, and SEO keywords in under 10 seconds. You can edit, regenerate, or use the content as-is.",
  },
  {
    question: "Is there a free plan?",
    answer:
      "Yes! Our Free plan includes 25 AI-generated listings, 500 leads, and basic CRM features. No credit card required. Upgrade anytime as your business grows.",
  },
  {
    question: "How does AI lead scoring work?",
    answer:
      "Our AI analyses each lead based on multiple factors: budget match with your listings, response time, engagement level, lead source quality, and property preferences. Each lead receives a score from 0–100, helping you prioritise the hottest leads first.",
  },
  {
    question: "Can I import leads from 99acres and MagicBricks?",
    answer:
      "Yes! You can import leads via CSV from any portal including 99acres, MagicBricks, Housing.com, and NoBroker. The system automatically deduplicates and scores imported leads.",
  },
  {
    question: "How does the WhatsApp integration work?",
    answer:
      "PropGenius connects to the WhatsApp Business API via Twilio. You can send and receive messages directly from the app, use pre-built templates for common scenarios, and get AI-suggested replies for incoming messages. You need a WhatsApp Business account to use this feature.",
  },
  {
    question: "Is my data secure?",
    answer:
      "Absolutely. We use Supabase with enterprise-grade security, row-level security (RLS) policies for data isolation, and all data is encrypted at rest and in transit. Your client data is never shared or used for AI training.",
  },
  {
    question: "Can I use PropGenius with my team?",
    answer:
      "Yes! Our Business plan supports up to 5 agents with role-based access control. Each agent can be assigned leads and has their own activity dashboard.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept all major Indian payment methods through Razorpay: credit/debit cards, UPI, net banking, and wallets. All prices are in INR with GST included.",
  },
  {
    question: "Can I cancel my subscription anytime?",
    answer:
      "Yes, you can cancel your subscription at any time from the Settings page. Your account will remain active until the end of your billing period. You can downgrade to the Free plan without losing your data.",
  },
];

/* ================================================================== */
/*  PAGE                                                               */
/* ================================================================== */

export default async function LandingPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <div className="min-h-screen bg-white">
      {/* ─── NAVBAR ─────────────────────────────────────────────── */}
      <header className="sticky top-0 z-50 border-b border-slate-100 bg-white/70 backdrop-blur-xl">
        <nav
          aria-label="Main navigation"
          className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"
        >
          <Link href="/" className="flex items-center gap-2.5">
            <Building2 className="h-7 w-7 text-primary-600" />
            <span className="text-xl font-bold tracking-tight text-slate-900">
              PropGenius
            </span>
            <Badge variant="primary" size="sm">
              AI
            </Badge>
          </Link>

          <div className="hidden items-center gap-8 md:flex">
            <a
              href="#features"
              className="text-sm font-medium text-slate-500 transition-colors hover:text-slate-900"
            >
              Features
            </a>
            <a
              href="#pricing"
              className="text-sm font-medium text-slate-500 transition-colors hover:text-slate-900"
            >
              Pricing
            </a>
            <a
              href="#faq"
              className="text-sm font-medium text-slate-500 transition-colors hover:text-slate-900"
            >
              FAQ
            </a>
          </div>

          <div className="flex items-center gap-3">
            {user ? (
              <Link
                href="/dashboard"
                className="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-primary-700"
              >
                <LayoutDashboard className="h-4 w-4" />
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link
                  href="/login"
                  className="text-sm font-medium text-slate-500 transition-colors hover:text-slate-900"
                >
                  Sign in
                </Link>
                <Link
                  href="/signup"
                  className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-slate-800"
                >
                  Get Started
                </Link>
              </>
            )}
          </div>
        </nav>
      </header>

      <main>
        {/* ─── HERO ─────────────────────────────────────────────── */}
        <section className="relative overflow-hidden pt-24 pb-20 sm:pt-32 sm:pb-28">
          {/* Background layers */}
          <div
            className="absolute inset-0 bg-linear-to-b from-slate-50 via-white to-white"
            aria-hidden="true"
          />
          <div
            className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_-20%,rgba(37,99,235,0.07),transparent)]"
            aria-hidden="true"
          />
          <div className="absolute inset-0 bg-grid-dots" aria-hidden="true" />

          <div className="relative mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-4xl text-center">
              {/* Badge */}
              <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-1.5 text-sm font-medium text-slate-600 shadow-sm animate-fade-in-up">
                <Sparkles className="h-3.5 w-3.5 text-primary-500" />
                AI-Powered Real Estate Platform
              </div>

              {/* Headline */}
              <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 leading-[1.08] sm:text-5xl lg:text-6xl xl:text-[4.25rem] animate-fade-in-up animate-delay-100">
                The Smarter Way to{" "}
                <span className="bg-linear-to-r from-primary-600 via-indigo-500 to-primary-500 animate-gradient-text">
                  Sell Real Estate
                </span>
              </h1>

              {/* Subtitle */}
              <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-slate-500 sm:text-xl animate-fade-in-up animate-delay-200">
                AI-powered listings, intelligent lead scoring, WhatsApp
                automation, and pipeline analytics — everything Indian real
                estate professionals need to close more deals.
              </p>

              {/* CTAs */}
              <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row animate-fade-in-up animate-delay-300">
                <Link
                  href="/signup"
                  className="btn-shine inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary-600 px-8 py-3.5 text-base font-semibold text-white shadow-xl shadow-primary-600/20 transition-all duration-300 hover:bg-primary-700 hover:shadow-2xl hover:shadow-primary-600/30 sm:w-auto"
                >
                  Get Started Free
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <a
                  href="#how-it-works"
                  className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-8 py-3.5 text-base font-medium text-slate-600 transition-all duration-300 hover:border-slate-300 hover:bg-slate-50 sm:w-auto"
                >
                  See How It Works
                </a>
              </div>

              <p className="mt-4 text-sm text-slate-400 animate-fade-in-up animate-delay-400">
                No credit card required &middot; Free plan available forever
              </p>

              {/* Capability pills */}
              <div className="mx-auto mt-16 flex flex-wrap items-center justify-center gap-3 animate-fade-in-up animate-delay-500">
                {(
                  [
                    { icon: Sparkles, label: "AI Listings" },
                    { icon: Users, label: "Lead CRM" },
                    { icon: MessageCircle, label: "WhatsApp" },
                    { icon: TrendingUp, label: "Analytics" },
                  ] as const
                ).map((item) => (
                  <div
                    key={item.label}
                    className="flex items-center gap-2 rounded-full border border-slate-200 bg-white/80 px-4 py-2 text-sm font-medium text-slate-600 shadow-sm backdrop-blur-sm"
                  >
                    <item.icon className="h-4 w-4 text-primary-500" />
                    {item.label}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* ─── INTEGRATIONS BAR ─────────────────────────────────── */}
        <section className="border-y border-slate-100 bg-slate-50/60 py-10">
          <div className="mx-auto max-w-5xl px-4 sm:px-6">
            <p className="mb-6 text-center text-xs font-semibold uppercase tracking-widest text-slate-400">
              Built with best-in-class technology
            </p>
            <div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-4">
              {INTEGRATIONS.map((name) => (
                <span
                  key={name}
                  className="text-base font-semibold text-slate-300 transition-colors hover:text-slate-500"
                >
                  {name}
                </span>
              ))}
            </div>
          </div>
        </section>

        {/* ─── HOW IT WORKS ─────────────────────────────────────── */}
        <section id="how-it-works" className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary-600">
                How It Works
              </p>
              <h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">
                Three Steps to Closing More Deals
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                From listing to conversion — simplified with AI
              </p>
            </div>

            <div className="relative mt-20 grid gap-12 md:grid-cols-3 md:gap-8">
              {/* Connector line (desktop) */}
              <div
                className="absolute top-10 left-[16.67%] hidden h-px w-[66.66%] border-t-2 border-dashed border-slate-200 md:block"
                aria-hidden="true"
              />

              {STEPS.map((step, i) => (
                <div
                  key={step.number}
                  className={`relative text-center animate-fade-in-up animate-delay-${(i + 1) * 100}`}
                >
                  <div className="relative z-10 mx-auto mb-8 flex h-20 w-20 items-center justify-center rounded-2xl border border-slate-200 bg-white text-2xl font-bold text-primary-600 shadow-sm">
                    {step.number}
                  </div>
                  <div className="mb-4 flex justify-center">
                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary-50">
                      <step.icon className="h-5 w-5 text-primary-500" />
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold text-slate-900">
                    {step.title}
                  </h3>
                  <p className="mx-auto mt-3 max-w-xs leading-relaxed text-slate-500">
                    {step.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── FEATURES ─────────────────────────────────────────── */}
        <section id="features" className="bg-slate-50/70 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary-600">
                Features
              </p>
              <h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">
                Six AI Features That Set You Apart
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Every feature is designed to save you time and close more deals
              </p>
            </div>

            <div className="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {AI_FEATURES.map((feature, i) => (
                <div
                  key={feature.title}
                  className={`group rounded-2xl border border-slate-200/80 bg-white p-8 transition-all duration-300 hover:border-slate-300 hover:shadow-xl hover:shadow-slate-200/40 animate-fade-in-up animate-delay-${(i + 1) * 100}`}
                >
                  <div
                    className={`flex h-11 w-11 items-center justify-center rounded-xl transition-transform duration-300 group-hover:scale-110 ${feature.accent}`}
                  >
                    <feature.icon className="h-5 w-5" />
                  </div>
                  <h3 className="mt-5 text-base font-semibold text-slate-900">
                    {feature.title}
                  </h3>
                  <p className="mt-2 text-sm leading-relaxed text-slate-500">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── DASHBOARD PREVIEW ────────────────────────────────── */}
        <section className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary-600">
                Product
              </p>
              <h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">
                Your Command Center for Real Estate
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Listings, leads, messages, and analytics — all in one powerful
                dashboard.
              </p>
            </div>

            <div className="mx-auto mt-16 max-w-5xl animate-fade-in-up">
              {/* Browser chrome */}
              <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl shadow-slate-300/30">
                {/* Title bar */}
                <div className="flex items-center gap-2 border-b border-slate-100 bg-slate-50 px-4 py-3">
                  <div className="flex gap-1.5">
                    <div className="h-3 w-3 rounded-full bg-slate-300" />
                    <div className="h-3 w-3 rounded-full bg-slate-300" />
                    <div className="h-3 w-3 rounded-full bg-slate-300" />
                  </div>
                  <div className="ml-4 flex-1 rounded-md bg-slate-100 px-3 py-1 text-xs text-slate-400">
                    app.propgenius.in/dashboard
                  </div>
                </div>

                {/* Dashboard content */}
                <div className="bg-linear-to-br from-slate-50 to-white p-6 sm:p-8">
                  {/* Stat cards */}
                  <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                    {[
                      {
                        label: "Active Listings",
                        value: "—",
                        color: "border-l-primary-500",
                      },
                      {
                        label: "Total Leads",
                        value: "—",
                        color: "border-l-green-500",
                      },
                      {
                        label: "Conversions",
                        value: "—",
                        color: "border-l-purple-500",
                      },
                      {
                        label: "AI Score Avg",
                        value: "—",
                        color: "border-l-orange-500",
                      },
                    ].map((card) => (
                      <div
                        key={card.label}
                        className={`rounded-lg border border-slate-200 border-l-4 ${card.color} bg-white p-3 shadow-sm`}
                      >
                        <p className="text-[11px] font-medium text-slate-400">
                          {card.label}
                        </p>
                        <p className="mt-1 text-xl font-bold text-slate-300">
                          {card.value}
                        </p>
                      </div>
                    ))}
                  </div>

                  {/* Chart + list */}
                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    {/* Chart placeholder */}
                    <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
                      <p className="text-xs font-medium text-slate-500">
                        Leads Over Time
                      </p>
                      <div className="mt-3 flex items-end gap-1.5">
                        {[40, 55, 35, 70, 45, 80, 65, 90, 75, 95, 85, 100].map(
                          (h, i) => (
                            <div
                              key={i}
                              className="flex-1 rounded-sm bg-primary-200"
                              style={{ height: `${h * 0.5}px` }}
                            />
                          )
                        )}
                      </div>
                    </div>

                    {/* Lead list placeholder */}
                    <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
                      <p className="text-xs font-medium text-slate-500">
                        Recent Leads
                      </p>
                      <div className="mt-3 space-y-2">
                        {[1, 2, 3].map((n) => (
                          <div
                            key={n}
                            className="flex items-center justify-between rounded-md bg-slate-50 px-3 py-2"
                          >
                            <div className="h-2.5 w-20 rounded-full bg-slate-200" />
                            <div className="h-5 w-10 rounded-full bg-slate-100" />
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ─── CRM & WHATSAPP DEEP DIVES ────────────────────────── */}
        <section className="bg-slate-50/70 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl space-y-28 px-4 sm:px-6">
            {/* Pipeline block */}
            <div className="grid items-center gap-12 md:grid-cols-2 lg:gap-20">
              <div className="space-y-6">
                <p className="text-sm font-semibold uppercase tracking-widest text-primary-600">
                  CRM
                </p>
                <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                  Visual Pipeline That Moves Deals Forward
                </h2>
                <p className="text-lg leading-relaxed text-slate-500">
                  Drag-and-drop Kanban board with 7 stages. See your entire
                  pipeline at a glance, track deal values, and never let a lead
                  slip through the cracks.
                </p>
                <ul className="space-y-3">
                  {CRM_PIPELINE_FEATURES.map((f) => (
                    <li key={f} className="flex items-center gap-3">
                      <Check className="h-5 w-5 shrink-0 text-success-500" />
                      <span className="text-slate-600">{f}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Mini Kanban */}
              <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-200/40">
                <div className="mb-4 flex items-center gap-2">
                  <KanbanSquare className="h-4 w-4 text-slate-400" />
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
                    Lead Pipeline
                  </span>
                </div>
                <div className="grid grid-cols-4 gap-2">
                  {[
                    { title: "New", color: "bg-blue-500", count: 2 },
                    { title: "Contacted", color: "bg-purple-500", count: 1 },
                    { title: "Site Visit", color: "bg-cyan-500", count: 2 },
                    { title: "Converted", color: "bg-green-500", count: 1 },
                  ].map((col) => (
                    <div key={col.title}>
                      <div className={`mb-2 h-1 rounded-full ${col.color}`} />
                      <p className="mb-2 text-[10px] font-semibold uppercase text-slate-400">
                        {col.title}
                      </p>
                      <div className="space-y-1.5">
                        {Array.from({ length: col.count }).map((_, i) => (
                          <div
                            key={i}
                            className="rounded-md border border-slate-100 bg-slate-50 px-2 py-2"
                          >
                            <div className="h-2 w-full rounded-full bg-slate-200" />
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* WhatsApp block */}
            <div className="grid items-center gap-12 md:grid-cols-2 lg:gap-20">
              {/* Chat mockup — left on desktop */}
              <div className="order-2 md:order-1">
                <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-200/40">
                  <div className="mb-4 flex items-center gap-2">
                    <MessageCircle className="h-4 w-4 text-green-500" />
                    <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
                      WhatsApp Chat
                    </span>
                  </div>
                  <div className="space-y-2.5">
                    {/* Incoming */}
                    <div className="max-w-[75%]">
                      <div className="rounded-xl rounded-tl-sm bg-slate-100 px-3.5 py-2.5 text-xs text-slate-700">
                        Hi, I saw your 3BHK listing in Andheri. Is it still
                        available?
                      </div>
                      <p className="mt-0.5 text-[10px] text-slate-400">
                        10:23 AM
                      </p>
                    </div>
                    {/* Outgoing */}
                    <div className="ml-auto max-w-[75%]">
                      <div className="rounded-xl rounded-tr-sm bg-green-500 px-3.5 py-2.5 text-xs text-white">
                        Yes! It&apos;s available. Would you like to schedule a
                        visit this weekend?
                      </div>
                      <p className="mt-0.5 text-right text-[10px] text-slate-400">
                        10:24 AM
                      </p>
                    </div>
                    {/* AI suggestions */}
                    <div className="rounded-lg border border-primary-100 bg-primary-50/50 p-2.5">
                      <p className="mb-1.5 flex items-center gap-1 text-[10px] font-semibold text-primary-600">
                        <Sparkles className="h-3 w-3" /> AI Suggestions
                      </p>
                      <div className="space-y-1">
                        <div className="rounded-md border border-primary-200/60 bg-white px-2.5 py-1.5 text-[10px] text-slate-600">
                          &quot;Saturday 11 AM works great! Shall I send the
                          location?&quot;
                        </div>
                        <div className="rounded-md border border-primary-200/60 bg-white px-2.5 py-1.5 text-[10px] text-slate-600">
                          &quot;The flat is 1,200 sqft with sea view. Photos
                          attached.&quot;
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="order-1 space-y-6 md:order-2">
                <p className="text-sm font-semibold uppercase tracking-widest text-primary-600">
                  Messaging
                </p>
                <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                  WhatsApp Built Right In
                </h2>
                <p className="text-lg leading-relaxed text-slate-500">
                  Send and receive WhatsApp messages without leaving PropGenius.
                  Use pre-built templates, get AI-suggested replies, and
                  auto-log every conversation to the lead timeline.
                </p>
                <ul className="space-y-3">
                  {WHATSAPP_FEATURES.map((f) => (
                    <li key={f} className="flex items-center gap-3">
                      <Check className="h-5 w-5 shrink-0 text-success-500" />
                      <span className="text-slate-600">{f}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* ─── AI POWER SECTION (dark) ──────────────────────────── */}
        <section className="relative overflow-hidden bg-slate-900 py-24 text-white sm:py-32">
          <div
            className="absolute inset-0 bg-grid-dots-light"
            aria-hidden="true"
          />
          <div
            className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(99,102,241,0.08),transparent_70%)]"
            aria-hidden="true"
          />

          <div className="relative mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary-400">
                AI Engine
              </p>
              <h2 className="mt-3 text-3xl font-bold text-white sm:text-4xl">
                The Intelligence Behind Every Decision
              </h2>
              <p className="mt-4 text-lg text-slate-400">
                See what AI can do for your business
              </p>
            </div>

            <div className="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {AI_EXAMPLES.map((item, i) => (
                <div
                  key={item.title}
                  className={`rounded-2xl border border-slate-700/60 bg-slate-800/40 p-6 backdrop-blur-sm transition-all duration-300 hover:border-slate-600 hover:bg-slate-800/70 animate-fade-in-up animate-delay-${(i + 1) * 100}`}
                >
                  <div
                    className={`flex h-10 w-10 items-center justify-center rounded-lg ${item.accent}`}
                  >
                    <item.icon className="h-5 w-5" />
                  </div>
                  <h3 className="mt-4 text-sm font-semibold text-white">
                    {item.title}
                  </h3>
                  <div className="mt-3 rounded-lg bg-slate-900/60 p-3">
                    <p className="whitespace-pre-line font-mono text-[11px] leading-relaxed text-slate-400">
                      {item.example}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── PRICING ──────────────────────────────────────────── */}
        <section id="pricing" className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary-600">
                Pricing
              </p>
              <h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">
                Simple, Transparent Pricing
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Start free. Upgrade when you&apos;re ready. Cancel anytime.
              </p>
            </div>

            <div className="mt-12">
              <PricingSection />
            </div>
          </div>
        </section>

        {/* ─── FAQ ──────────────────────────────────────────────── */}
        <section id="faq" className="border-t border-slate-100 py-24 sm:py-32">
          <div className="mx-auto max-w-3xl px-4 sm:px-6">
            <div className="text-center">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary-600">
                FAQ
              </p>
              <h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">
                Frequently Asked Questions
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Everything you need to know about PropGenius AI
              </p>
            </div>

            <div className="mt-12">
              <FaqAccordion items={FAQ_ITEMS} />
            </div>
          </div>
        </section>

        {/* ─── FINAL CTA ────────────────────────────────────────── */}
        <section className="relative overflow-hidden py-24 sm:py-32">
          <div
            className="absolute inset-0 bg-linear-to-br from-slate-900 via-slate-800 to-slate-900"
            aria-hidden="true"
          />
          <div
            className="absolute inset-0 bg-[radial-gradient(ellipse_at_bottom_right,rgba(59,130,246,0.12),transparent_70%)]"
            aria-hidden="true"
          />
          <div className="absolute inset-0 bg-grid-dots-light" aria-hidden="true" />

          <div className="relative mx-auto max-w-3xl px-4 text-center sm:px-6">
            <h2 className="text-3xl font-bold text-white sm:text-4xl lg:text-5xl">
              Ready to Transform Your Real Estate Business?
            </h2>
            <p className="mx-auto mt-6 max-w-xl text-lg text-slate-400">
              Join real estate professionals across India who are closing deals
              faster with PropGenius AI.
            </p>
            <Link
              href="/signup"
              className="btn-shine mt-10 inline-flex items-center gap-2 rounded-xl bg-white px-8 py-4 text-base font-semibold text-slate-900 shadow-xl transition-all duration-300 hover:bg-slate-50 hover:shadow-2xl"
            >
              Get Started Free
              <ArrowRight className="h-4 w-4" />
            </Link>
            <p className="mt-4 text-sm text-slate-500">
              No credit card required
            </p>
          </div>
        </section>
      </main>

      {/* ─── FOOTER ─────────────────────────────────────────────── */}
      <footer className="border-t border-slate-100 bg-white pt-16 pb-8">
        <div className="mx-auto max-w-7xl px-4 sm:px-6">
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {/* Brand */}
            <div>
              <div className="flex items-center gap-2">
                <Building2 className="h-6 w-6 text-primary-600" />
                <span className="text-lg font-bold text-slate-900">
                  PropGenius AI
                </span>
              </div>
              <p className="mt-3 text-sm leading-relaxed text-slate-500">
                AI-powered real estate CRM built for India&apos;s top agents and
                agencies.
              </p>
              <div className="mt-4 flex items-center gap-3">
                {[
                  { icon: Globe, label: "Website" },
                  { icon: MessageCircle, label: "Chat" },
                ].map((social) => (
                  <span
                    key={social.label}
                    className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-slate-400 transition-colors hover:bg-primary-50 hover:text-primary-600"
                  >
                    <social.icon className="h-4 w-4" />
                  </span>
                ))}
              </div>
            </div>

            {/* Product */}
            <div>
              <h4 className="text-sm font-semibold uppercase tracking-wider text-slate-900">
                Product
              </h4>
              <ul className="mt-4 space-y-3">
                {[
                  { label: "Features", href: "#features" },
                  { label: "Pricing", href: "#pricing" },
                  { label: "FAQ", href: "#faq" },
                  { label: "Dashboard", href: "/login" },
                ].map((link) => (
                  <li key={link.label}>
                    <a
                      href={link.href}
                      className="text-sm text-slate-500 transition-colors hover:text-slate-900"
                    >
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            {/* Resources */}
            <div>
              <h4 className="text-sm font-semibold uppercase tracking-wider text-slate-900">
                Resources
              </h4>
              <ul className="mt-4 space-y-3">
                {["Blog", "Help Center", "API Documentation", "Status Page"].map(
                  (label) => (
                    <li key={label}>
                      <span className="cursor-pointer text-sm text-slate-500 transition-colors hover:text-slate-900">
                        {label}
                      </span>
                    </li>
                  )
                )}
              </ul>
            </div>

            {/* Legal */}
            <div>
              <h4 className="text-sm font-semibold uppercase tracking-wider text-slate-900">
                Legal
              </h4>
              <ul className="mt-4 space-y-3">
                {[
                  "Privacy Policy",
                  "Terms of Service",
                  "Refund Policy",
                  "RERA Compliance",
                ].map((label) => (
                  <li key={label}>
                    <span className="cursor-pointer text-sm text-slate-500 transition-colors hover:text-slate-900">
                      {label}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Bottom bar */}
          <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-slate-100 pt-8 sm:flex-row">
            <p className="text-sm text-slate-400">
              &copy; {new Date().getFullYear()} PropGenius AI. All rights
              reserved.
            </p>
            <p className="flex items-center gap-1.5 text-sm text-slate-400">
              Made with{" "}
              <Heart className="h-3.5 w-3.5 fill-red-500 text-red-500" /> in
              India
            </p>
            <div className="flex items-center gap-1.5 text-sm text-slate-400">
              <Zap className="h-3.5 w-3.5 text-primary-500" />
              Powered by AI
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
