import Link from "next/link";
import {
  Building2,
  Sparkles,
  ArrowRight,
  Play,
  FileText,
  Users,
  Trophy,
  Brain,
  MessageSquareText,
  Building,
  CalendarClock,
  TrendingUp,
  Check,
  KanbanSquare,
  MessageCircle,
  Star,
  Heart,
  Quote,
  Zap,
  Globe,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { PricingSection } from "@/components/landing/pricing-toggle";
import { FaqAccordion } from "@/components/landing/faq-accordion";
import { getInitials } from "@/lib/utils";

/* ================================================================== */
/*  DATA CONSTANTS                                                     */
/* ================================================================== */

const STATS = [
  { value: "10x", label: "Faster Listings" },
  { value: "2,500+", label: "Active Agents" },
  { value: "50K+", label: "Leads Managed" },
  { value: "98%", label: "Satisfaction Rate" },
];

const PARTNERS = [
  "99acres", "MagicBricks", "Housing.com", "NoBroker",
  "Razorpay", "WhatsApp Business", "Supabase", "Google Gemini",
];

const STEPS = [
  {
    number: "01",
    icon: FileText,
    title: "Create AI Listings",
    description: "Enter basic property details. Our AI generates professional titles, descriptions, social media posts, and SEO-optimized content in seconds.",
  },
  {
    number: "02",
    icon: Users,
    title: "Manage & Score Leads",
    description: "Import leads from 99acres, MagicBricks, or CSV. AI scores each lead 0-100 and prioritizes your follow-ups automatically.",
  },
  {
    number: "03",
    icon: Trophy,
    title: "Close Deals Faster",
    description: "Use WhatsApp smart replies, AI follow-up suggestions, and pipeline analytics to convert more leads into happy homeowners.",
  },
];

const AI_FEATURES = [
  {
    icon: Sparkles,
    title: "AI Listing Generator",
    description: "Enter property details, get professional titles, vivid descriptions, social media posts, and SEO tags — all generated by Google Gemini in under 10 seconds.",
    accent: "bg-primary-50 text-primary-600",
  },
  {
    icon: Users,
    title: "Smart CRM",
    description:
      "Manage leads with AI scoring, pipeline view, activity timeline, and CSV import. Never miss a follow-up.",
  },
  {
    icon: MessageSquareText,
    title: "AI Smart Reply",
    description: "Get 3 contextual WhatsApp reply suggestions for every incoming message. One tap to send. Never leave a lead waiting.",
    accent: "bg-success-50 text-success-600",
  },
  {
    icon: Building,
    title: "AI Property Matching",
    description: "Automatically match incoming leads to your best-fit listings based on budget, location preferences, and property type.",
    accent: "bg-warning-50 text-warning-600",
  },
  {
    icon: CalendarClock,
    title: "AI Follow-Up Engine",
    description: "AI recommends the optimal time, channel (WhatsApp/call/email), and talking points for each follow-up. Never miss the right moment.",
    accent: "bg-purple-50 text-purple-600",
  },
  {
    icon: TrendingUp,
    title: "AI Listing Optimizer",
    description: "Already have listings? Our AI analyzes and suggests improvements to titles, descriptions, and pricing to increase lead generation.",
    accent: "bg-cyan-50 text-cyan-600",
  },
];

const AI_EXAMPLES = [
  {
    icon: Sparkles,
    title: "Listing Generator",
    example: "\"Luxurious 3BHK in Bandra West with sea-facing balcony, modular kitchen, and 24/7 security. Premium amenities include infinity pool, gymnasium...\"",
    accent: "text-primary-400 bg-primary-500/10",
  },
  {
    icon: Brain,
    title: "Lead Scoring",
    example: "Score: 87/100 — Hot Lead\nBudget match: High\nResponse time: Fast\nSource: Referral (premium)",
    accent: "text-info-400 bg-info-500/10",
  },
  {
    icon: MessageSquareText,
    title: "Smart Reply",
    example: "1. \"Yes, the flat is available for viewing this weekend...\"\n2. \"I can schedule a visit for Saturday at 11 AM...\"\n3. \"The asking price is negotiable for serious buyers...\"",
    accent: "text-green-400 bg-green-500/10",
  },
  {
    icon: Building,
    title: "Property Matching",
    example: "3 matching listings found for Rajesh's requirements:\n• Sea View 3BHK Andheri — 92% match\n• Premium 3BHK Goregaon — 78% match",
    accent: "text-yellow-400 bg-yellow-500/10",
  },
  {
    icon: CalendarClock,
    title: "Follow-Up Engine",
    example: "Call Priya tomorrow at 11 AM about the Andheri flat — she viewed it twice this week. Mention the new price drop.",
    accent: "text-purple-400 bg-purple-500/10",
  },
  {
    icon: TrendingUp,
    title: "Listing Optimizer",
    example: "Score: 6/10 — 3 suggestions:\n• Add carpet area to title (+28% views)\n• Mention nearby metro station\n• Update price to market rate",
    accent: "text-cyan-400 bg-cyan-500/10",
  },
];

const CRM_PIPELINE_FEATURES = [
  "Drag-and-drop lead management",
  "7-stage customizable pipeline",
  "Activity timeline for every lead",
  "CSV import from 99acres & MagicBricks",
  "AI-powered lead scoring & matching",
];

const WHATSAPP_FEATURES = [
  "Two-way WhatsApp messaging",
  "Pre-built & custom message templates",
  "AI smart reply suggestions",
  "Auto-logged to lead activity",
  "Browser & email notifications",
];

const TESTIMONIALS = [
  {
    quote: "PropGenius cut our listing creation time from 45 minutes to under 2 minutes. The AI-generated descriptions are so good that buyers think we hired a professional copywriter.",
    name: "Rajesh Sharma",
    role: "Senior Agent",
    company: "Sharma Properties, Mumbai",
  },
  {
    quote: "The lead scoring feature alone is worth the subscription. We stopped chasing cold leads and our conversion rate jumped from 3% to 11% in just two months.",
    name: "Priya Patel",
    role: "Broker Owner",
    company: "Patel Realty Group, Ahmedabad",
  },
  {
    quote: "WhatsApp integration changed everything. We respond to leads in seconds with AI-suggested replies. Our team of 4 agents manages 200+ active leads effortlessly.",
    name: "Vikram Malhotra",
    role: "Agency Director",
    company: "Urban Nest Properties, Delhi NCR",
  },
];

const FAQ_ITEMS = [
  {
    question: "What is PropGenius AI?",
    answer: "PropGenius AI is an all-in-one real estate platform built for Indian agents and agencies. It combines AI-powered listing generation, smart CRM with lead scoring, WhatsApp integration, and analytics dashboard to help you close more deals faster.",
  },
  {
    question: "How does the AI listing generator work?",
    answer: "Simply enter your property details — type, location, price, bedrooms, amenities — and our AI (powered by Google Gemini) generates a professional title, detailed description, social media post, and SEO keywords in under 10 seconds. You can edit, regenerate, or use the content as-is.",
  },
  {
    question: "Is there a free plan?",
    answer: "Yes! Our Free plan includes 5 AI-generated listings per month, up to 50 leads, and basic CRM features. No credit card required. Upgrade anytime as your business grows.",
  },
  {
    question: "How does AI lead scoring work?",
    answer: "Our AI analyzes each lead based on multiple factors: budget match with your listings, response time, engagement level, lead source quality, and property preferences. Each lead receives a score from 0-100, helping you prioritize the hottest leads first.",
  },
  {
    question: "Can I import leads from 99acres and MagicBricks?",
    answer: "Yes! You can import leads via CSV from any portal including 99acres, MagicBricks, Housing.com, and NoBroker. The system automatically deduplicates and scores imported leads.",
  },
  {
    question: "How does the WhatsApp integration work?",
    answer: "PropGenius connects to the WhatsApp Business API via Twilio. You can send and receive messages directly from the app, use pre-built templates for common scenarios, and get AI-suggested replies for incoming messages. You need a WhatsApp Business account to use this feature.",
  },
  {
    question: "Is my data secure?",
    answer: "Absolutely. We use Supabase with enterprise-grade security, row-level security (RLS) policies for data isolation, and all data is encrypted at rest and in transit. Your client data is never shared or used for AI training.",
  },
  {
    question: "Can I use PropGenius with my team?",
    answer: "Yes! Our Business plan supports up to 5 agents with role-based access control. The Enterprise plan supports unlimited agents. Each agent can be assigned leads and has their own activity dashboard.",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept all major Indian payment methods through Razorpay: credit/debit cards, UPI, net banking, and wallets. All prices are in INR with GST included.",
  },
  {
    question: "Can I cancel my subscription anytime?",
    answer: "Yes, you can cancel your subscription at any time from the Settings page. Your account will remain active until the end of your billing period. You can downgrade to the Free plan without losing your data.",
  },
];

/* ================================================================== */
/*  PAGE COMPONENT                                                     */
/* ================================================================== */

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* ============================================================ */}
      {/* 1. NAVBAR                                                     */}
      {/* ============================================================ */}
      <header className="sticky top-0 z-50 border-b border-slate-200/60 bg-white/80 backdrop-blur-lg">
        <nav aria-label="Main navigation" className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2">
            <Building2 className="h-7 w-7 text-primary-600" />
            <span className="text-xl font-bold text-slate-900">PropGenius</span>
            <Badge variant="primary" size="sm">AI</Badge>
          </Link>

          <div className="hidden items-center gap-8 md:flex">
            <a href="#features" className="text-sm font-medium text-slate-600 transition-colors hover:text-slate-900">Features</a>
            <a href="#pricing" className="text-sm font-medium text-slate-600 transition-colors hover:text-slate-900">Pricing</a>
            <a href="#faq" className="text-sm font-medium text-slate-600 transition-colors hover:text-slate-900">FAQ</a>
          </div>

          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm font-medium text-slate-600 transition-colors hover:text-slate-900">
              Sign in
            </Link>
            <Link
              href="/signup"
              className="rounded-xl bg-primary-600 px-5 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-primary-700"
            >
              Start Free
            </Link>
          </div>
        </nav>
      </header>

      <main>
        {/* ============================================================ */}
        {/* 2. HERO                                                       */}
        {/* ============================================================ */}
        <section className="relative overflow-hidden pt-20 pb-24 sm:pt-28 sm:pb-32">
          {/* Background */}
          <div className="absolute inset-0 bg-gradient-to-b from-primary-50/50 via-white to-white" aria-hidden="true" />
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(59,130,246,0.08),transparent_70%)]" aria-hidden="true" />

          {/* Floating blobs */}
          <div className="absolute -left-32 top-20 h-72 w-72 rounded-full bg-primary-200/20 blur-3xl animate-float" aria-hidden="true" />
          <div className="absolute -right-32 top-40 h-64 w-64 rounded-full bg-indigo-200/20 blur-3xl animate-float animate-delay-300" aria-hidden="true" />

          <div className="relative mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-4xl text-center">
              {/* Badge */}
              <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-primary-200 bg-primary-50 px-4 py-1.5 text-sm font-medium text-primary-700 animate-fade-in-up">
                <Sparkles className="h-4 w-4" />
                Powered by Google Gemini AI
              </div>

              {/* Headline */}
              <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 leading-[1.1] sm:text-5xl lg:text-6xl animate-fade-in-up animate-delay-100">
                Close Deals Faster with{" "}
                <span className="bg-gradient-to-r from-primary-600 via-indigo-500 to-primary-600 animate-gradient-text">
                  AI-Powered
                </span>{" "}
                Real Estate CRM
              </h1>

              {/* Subtitle */}
              <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-slate-600 sm:text-xl animate-fade-in-up animate-delay-200">
                Generate professional listings in seconds, score leads with AI,
                automate WhatsApp follow-ups, and manage your entire pipeline —
                built specifically for Indian real estate agents.
              </p>

              {/* CTAs */}
              <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row animate-fade-in-up animate-delay-300">
                <Link
                  href="/signup"
                  className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary-600 px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-primary-600/25 transition-all duration-200 hover:bg-primary-700 hover:shadow-xl hover:shadow-primary-600/30 animate-pulse-glow sm:w-auto"
                >
                  Start Free Trial
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <a
                  href="#how-it-works"
                  className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-8 py-3.5 text-base font-semibold text-slate-700 transition-all duration-200 hover:border-slate-400 hover:bg-slate-50 sm:w-auto"
                >
                  <Play className="h-4 w-4" />
                  See How It Works
                </a>
              </div>

              <p className="mt-4 text-sm text-slate-400 animate-fade-in-up animate-delay-400">
                No credit card required. Free forever on starter plan.
              </p>

              {/* Stats */}
              <div className="mx-auto mt-16 grid max-w-3xl grid-cols-2 gap-6 md:grid-cols-4">
                {STATS.map((stat, i) => (
                  <div
                    key={stat.label}
                    className={`text-center animate-count-up animate-delay-${(i + 1) * 100}`}
                  >
                    <p className="text-3xl font-extrabold text-slate-900">{stat.value}</p>
                    <p className="mt-1 text-sm text-slate-500">{stat.label}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 3. SOCIAL PROOF BAR                                           */}
        {/* ============================================================ */}
        <section className="overflow-hidden border-y border-slate-100 bg-slate-50/50 py-10">
          <p className="mb-6 text-center text-sm font-medium uppercase tracking-wider text-slate-400">
            Trusted by 2,500+ real estate professionals across India
          </p>
          <div className="relative" aria-hidden="true">
            <div className="flex animate-slide-left items-center gap-12">
              {[...PARTNERS, ...PARTNERS].map((name, i) => (
                <span key={`${name}-${i}`} className="whitespace-nowrap text-lg font-semibold text-slate-300 transition-colors hover:text-slate-500">
                  {name}
                </span>
              ))}
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 4. HOW IT WORKS                                               */}
        {/* ============================================================ */}
        <section id="how-it-works" className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                How PropGenius Works
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Go from zero to closed deal in three simple steps
              </p>
            </div>

            <div className="relative mt-16 grid gap-12 md:grid-cols-3 md:gap-8">
              {/* Connector lines */}
              <div className="absolute top-14 left-[calc(33.33%_-_16px)] hidden h-px w-[calc(33.33%_+_32px)] border-t-2 border-dashed border-slate-200 md:block" aria-hidden="true" />
              <div className="absolute top-14 left-[calc(66.66%_-_16px)] hidden h-px w-[calc(33.33%_+_32px)] border-t-2 border-dashed border-slate-200 md:block" aria-hidden="true" />

              {STEPS.map((step, i) => (
                <div key={step.number} className={`relative text-center animate-fade-in-up animate-delay-${(i + 1) * 100}`}>
                  <div className="mb-6 inline-flex h-14 w-14 items-center justify-center rounded-full bg-primary-600 text-lg font-bold text-white shadow-lg shadow-primary-600/25">
                    {step.number}
                  </div>
                  <div className="mb-4 flex justify-center">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary-50">
                      <step.icon className="h-6 w-6 text-primary-500" />
                    </div>
                  </div>
                  <h3 className="text-xl font-semibold text-slate-900">{step.title}</h3>
                  <p className="mt-3 leading-relaxed text-slate-500">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 5. FEATURE SHOWCASE (6 AI Features)                           */}
        {/* ============================================================ */}
        <section id="features" className="bg-slate-50 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                6 AI Features That Set You Apart
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Every feature is designed to save you time and close more deals
              </p>
            </div>

            <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {AI_FEATURES.map((feature, i) => (
                <div
                  key={feature.title}
                  className={`group rounded-2xl border border-slate-200 bg-white p-8 transition-all duration-300 hover:border-slate-300 hover:shadow-lg hover:shadow-slate-200/50 animate-fade-in-up animate-delay-${(i + 1) * 100}`}
                >
                  <div className={`flex h-12 w-12 items-center justify-center rounded-xl transition-transform duration-300 group-hover:-translate-y-0.5 ${feature.accent}`}>
                    <feature.icon className="h-6 w-6" />
                  </div>
                  <h3 className="mt-5 text-lg font-semibold text-slate-900">{feature.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-slate-500">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 6. PRODUCT SCREENSHOT / DEMO                                  */}
        {/* ============================================================ */}
        <section className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                Your Command Center for Real Estate
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                A powerful dashboard that puts everything at your fingertips — listings, leads, messages, and analytics.
              </p>
            </div>

            <div className="mx-auto mt-16 max-w-5xl animate-fade-in-up">
              {/* Browser frame */}
              <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl shadow-slate-200/50">
                {/* Chrome bar */}
                <div className="flex items-center gap-2 border-b border-slate-100 bg-slate-50 px-4 py-3">
                  <div className="flex gap-1.5">
                    <div className="h-3 w-3 rounded-full bg-red-400" />
                    <div className="h-3 w-3 rounded-full bg-yellow-400" />
                    <div className="h-3 w-3 rounded-full bg-green-400" />
                  </div>
                  <div className="ml-4 flex-1 rounded-md bg-slate-100 px-3 py-1 text-xs text-slate-400">
                    app.propgenius.in/dashboard
                  </div>
                </div>

                {/* Mock dashboard */}
                <div className="bg-gradient-to-br from-slate-50 to-slate-100 p-6 sm:p-8">
                  {/* Stat row */}
                  <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                    {[
                      { label: "Active Listings", value: "24", color: "border-l-primary-500" },
                      { label: "Total Leads", value: "187", color: "border-l-green-500" },
                      { label: "Conversions", value: "12", color: "border-l-purple-500" },
                      { label: "AI Score Avg", value: "72", color: "border-l-orange-500" },
                    ].map((card) => (
                      <div key={card.label} className={`rounded-lg border border-slate-200 border-l-4 ${card.color} bg-white p-3 shadow-sm`}>
                        <p className="text-xs text-slate-400">{card.label}</p>
                        <p className="mt-1 text-xl font-bold text-slate-900">{card.value}</p>
                      </div>
                    ))}
                  </div>

                  {/* Chart + List row */}
                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    {/* Mini chart */}
                    <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
                      <p className="text-xs font-medium text-slate-500">Leads Over Time</p>
                      <div className="mt-3 flex items-end gap-1.5">
                        {[40, 55, 35, 70, 45, 80, 65, 90, 75, 95, 85, 100].map((h, i) => (
                          <div
                            key={i}
                            className="flex-1 rounded-sm bg-primary-400"
                            style={{ height: `${h * 0.6}px` }}
                          />
                        ))}
                      </div>
                    </div>

                    {/* Mini lead list */}
                    <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
                      <p className="text-xs font-medium text-slate-500">Recent Leads</p>
                      <div className="mt-3 space-y-2">
                        {[
                          { name: "Amit K.", score: 87, status: "Hot" },
                          { name: "Sneha R.", score: 64, status: "Warm" },
                          { name: "Ravi M.", score: 92, status: "Hot" },
                        ].map((lead) => (
                          <div key={lead.name} className="flex items-center justify-between rounded-md bg-slate-50 px-3 py-1.5">
                            <span className="text-xs font-medium text-slate-700">{lead.name}</span>
                            <div className="flex items-center gap-2">
                              <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${lead.score > 70 ? "bg-green-100 text-green-700" : "bg-yellow-100 text-yellow-700"}`}>
                                {lead.score}
                              </span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 7. CRM FEATURES (Alternating Layout)                          */}
        {/* ============================================================ */}
        <section className="bg-slate-50 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl space-y-24 px-4 sm:px-6">
            {/* Block 1 — Pipeline */}
            <div className="grid items-center gap-12 md:grid-cols-2 lg:gap-20">
              <div className="space-y-6">
                <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                  Visual Pipeline That Moves Deals Forward
                </h2>
                <p className="text-lg leading-relaxed text-slate-600">
                  Drag-and-drop Kanban board with 7 stages. See your entire pipeline at a glance, track deal values, and never let a lead slip through the cracks.
                </p>
                <ul className="space-y-3">
                  {CRM_PIPELINE_FEATURES.map((f) => (
                    <li key={f} className="flex items-center gap-3">
                      <Check className="h-5 w-5 shrink-0 text-success-500" />
                      <span className="text-slate-600">{f}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Visual: Mini Kanban */}
              <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-lg">
                <div className="mb-3 flex items-center gap-2">
                  <KanbanSquare className="h-4 w-4 text-slate-400" />
                  <span className="text-xs font-semibold text-slate-500">LEAD PIPELINE</span>
                </div>
                <div className="grid grid-cols-4 gap-2">
                  {[
                    { title: "New", color: "bg-blue-500", cards: ["Amit K.", "Sneha R."] },
                    { title: "Contacted", color: "bg-purple-500", cards: ["Ravi M."] },
                    { title: "Site Visit", color: "bg-cyan-500", cards: ["Priya P.", "Vikram S."] },
                    { title: "Converted", color: "bg-green-500", cards: ["Meena J."] },
                  ].map((col) => (
                    <div key={col.title}>
                      <div className={`mb-2 h-1 rounded-full ${col.color}`} />
                      <p className="mb-2 text-[10px] font-semibold uppercase text-slate-400">{col.title}</p>
                      <div className="space-y-1.5">
                        {col.cards.map((name) => (
                          <div key={name} className="rounded-md border border-slate-100 bg-slate-50 px-2 py-1.5 text-[11px] font-medium text-slate-600">
                            {name}
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Block 2 — WhatsApp */}
            <div className="grid items-center gap-12 md:grid-cols-2 lg:gap-20">
              {/* Visual: Chat mockup — First on mobile, second on desktop */}
              <div className="order-2 md:order-1">
                <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-lg">
                  <div className="mb-3 flex items-center gap-2">
                    <MessageCircle className="h-4 w-4 text-green-500" />
                    <span className="text-xs font-semibold text-slate-500">WHATSAPP CHAT</span>
                  </div>
                  <div className="space-y-2.5">
                    {/* Incoming */}
                    <div className="max-w-[75%]">
                      <div className="rounded-xl rounded-tl-sm bg-slate-100 px-3.5 py-2.5 text-xs text-slate-700">
                        Hi, I saw your 3BHK listing in Andheri. Is it still available?
                      </div>
                      <p className="mt-0.5 text-[10px] text-slate-400">10:23 AM</p>
                    </div>
                    {/* Outgoing */}
                    <div className="ml-auto max-w-[75%]">
                      <div className="rounded-xl rounded-tr-sm bg-green-500 px-3.5 py-2.5 text-xs text-white">
                        Yes! It&apos;s available. Would you like to schedule a visit this weekend?
                      </div>
                      <p className="mt-0.5 text-right text-[10px] text-slate-400">10:24 AM</p>
                    </div>
                    {/* AI suggestion bar */}
                    <div className="rounded-lg bg-blue-50 p-2.5">
                      <p className="mb-1.5 flex items-center gap-1 text-[10px] font-semibold text-primary-600">
                        <Sparkles className="h-3 w-3" /> AI Suggestions
                      </p>
                      <div className="space-y-1">
                        <div className="rounded-md border border-blue-200 bg-white px-2.5 py-1 text-[10px] text-slate-600">
                          &quot;Saturday 11 AM works great! Shall I send the location?&quot;
                        </div>
                        <div className="rounded-md border border-blue-200 bg-white px-2.5 py-1 text-[10px] text-slate-600">
                          &quot;The flat is 1,200 sqft with sea view. Photos attached.&quot;
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="order-1 space-y-6 md:order-2">
                <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                  WhatsApp Built Right In
                </h2>
                <p className="text-lg leading-relaxed text-slate-600">
                  Send and receive WhatsApp messages without leaving PropGenius. Use pre-built templates, get AI-suggested replies, and auto-log every conversation to the lead timeline.
                </p>
                <ul className="space-y-3">
                  {WHATSAPP_FEATURES.map((f) => (
                    <li key={f} className="flex items-center gap-3">
                      <Check className="h-5 w-5 shrink-0 text-success-500" />
                      <span className="text-slate-600">{f}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 8. AI POWER SECTION (Dark Theme)                              */}
        {/* ============================================================ */}
        <section className="relative py-24 sm:py-32 bg-slate-900 text-white overflow-hidden">
          {/* Grid pattern */}
          <div
            className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.03)_1px,transparent_1px)] bg-[size:64px_64px]"
            aria-hidden="true"
          />

          <div className="relative mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold text-white sm:text-4xl">
                The AI Brain Behind Every Decision
              </h2>
              <p className="mt-4 text-lg text-slate-400">
                Powered by Google Gemini 2.5 Flash — the same AI that powers Google Search
              </p>
            </div>

            <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {AI_EXAMPLES.map((item, i) => (
                <div
                  key={item.title}
                  className={`rounded-2xl border border-slate-700/50 bg-slate-800/50 p-6 backdrop-blur-sm transition-all duration-300 hover:border-slate-600 hover:bg-slate-800 animate-fade-in-up animate-delay-${(i + 1) * 100}`}
                >
                  <div className={`flex h-10 w-10 items-center justify-center rounded-lg ${item.accent}`}>
                    <item.icon className="h-5 w-5" />
                  </div>
                  <h3 className="mt-4 text-base font-semibold text-white">{item.title}</h3>
                  <div className="mt-3 rounded-lg bg-slate-900/50 p-3">
                    <p className="whitespace-pre-line font-mono text-xs leading-relaxed text-slate-400">
                      {item.example}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 9. PRICING                                                    */}
        {/* ============================================================ */}
        <section id="pricing" className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                Simple, Transparent Pricing
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Start free. Upgrade when you&apos;re ready. No hidden fees, cancel anytime.
              </p>
            </div>

            <div className="mt-12">
              <PricingSection />
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 10. TESTIMONIALS                                              */}
        {/* ============================================================ */}
        <section className="bg-slate-50 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                Loved by Real Estate Professionals
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                See what agents across India are saying about PropGenius
              </p>
            </div>

            <div className="mt-16 grid gap-8 md:grid-cols-3">
              {TESTIMONIALS.map((t) => (
                <article
                  key={t.name}
                  className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"
                >
                  {/* Stars */}
                  <div className="flex gap-0.5">
                    {Array.from({ length: 5 }).map((_, i) => (
                      <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>

                  {/* Quote */}
                  <blockquote className="mt-4 leading-relaxed text-slate-600">
                    <Quote className="mb-2 h-6 w-6 text-slate-200" aria-hidden="true" />
                    {t.quote}
                  </blockquote>

                  {/* Author */}
                  <div className="mt-6 flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-100 text-sm font-bold text-primary-600">
                      {getInitials(t.name)}
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-slate-900">{t.name}</p>
                      <p className="text-xs text-slate-500">{t.role}, {t.company}</p>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 11. FAQ                                                       */}
        {/* ============================================================ */}
        <section id="faq" className="py-24 sm:py-32">
          <div className="mx-auto max-w-3xl px-4 sm:px-6">
            <div className="text-center">
              <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">
                Frequently Asked Questions
              </h2>
              <p className="mt-4 text-lg text-slate-500">
                Everything you need to know about PropGenius AI
              </p>
            </div>

            <div className="mt-12">
              <FaqAccordion items={FAQ_ITEMS} />
            </div>
          </div>
        </section>

        {/* ============================================================ */}
        {/* 12. FINAL CTA                                                 */}
        {/* ============================================================ */}
        <section className="relative overflow-hidden py-24 sm:py-32">
          <div className="absolute inset-0 bg-gradient-to-br from-primary-600 via-primary-700 to-indigo-800" aria-hidden="true" />
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_bottom_right,rgba(255,255,255,0.1),transparent_70%)]" aria-hidden="true" />

          <div className="relative mx-auto max-w-3xl px-4 text-center sm:px-6">
            <h2 className="text-3xl font-bold text-white sm:text-4xl lg:text-5xl">
              Ready to Transform Your Real Estate Business?
            </h2>
            <p className="mx-auto mt-6 max-w-2xl text-lg text-primary-100">
              Join 2,500+ Indian real estate professionals who close deals faster with PropGenius AI.
            </p>
            <Link
              href="/signup"
              className="mt-10 inline-flex items-center gap-2 rounded-xl bg-white px-8 py-4 text-base font-semibold text-primary-700 shadow-xl transition-all duration-200 hover:bg-primary-50 animate-pulse-glow"
            >
              Get Started Free — No Credit Card Required
              <ArrowRight className="h-4 w-4" />
            </Link>
            <div className="mt-4">
              <a href="#pricing" className="text-sm text-primary-200 underline underline-offset-4 transition-colors hover:text-white">
                Or compare pricing plans
              </a>
            </div>
          </div>
        </section>
      </main>

      {/* ============================================================ */}
      {/* 13. FOOTER                                                    */}
      {/* ============================================================ */}
      <footer className="border-t border-slate-200 bg-white pt-16 pb-8">
        <div className="mx-auto max-w-7xl px-4 sm:px-6">
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {/* Company */}
            <div>
              <div className="flex items-center gap-2">
                <Building2 className="h-6 w-6 text-primary-600" />
                <span className="text-lg font-bold text-slate-900">PropGenius AI</span>
              </div>
              <p className="mt-3 text-sm leading-relaxed text-slate-500">
                AI-powered real estate CRM built for India&apos;s top agents and agencies.
              </p>
              <div className="mt-4 flex items-center gap-3">
                {[
                  { icon: Globe, label: "Website" },
                  { icon: MessageCircle, label: "Chat" },
                ].map((social) => (
                  <span
                    key={social.label}
                    className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-slate-400 transition-colors hover:bg-primary-50 hover:text-primary-600"
                  >
                    <social.icon className="h-4 w-4" />
                  </span>
                ))}
              </div>
            </div>

            {/* Product */}
            <div>
              <h4 className="text-sm font-semibold uppercase tracking-wider text-slate-900">Product</h4>
              <ul className="mt-4 space-y-3">
                {[
                  { label: "Features", href: "#features" },
                  { label: "Pricing", href: "#pricing" },
                  { label: "FAQ", href: "#faq" },
                  { label: "Dashboard", href: "/login" },
                ].map((link) => (
                  <li key={link.label}>
                    <a href={link.href} className="text-sm text-slate-500 transition-colors hover:text-slate-900">
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            {/* Resources */}
            <div>
              <h4 className="text-sm font-semibold uppercase tracking-wider text-slate-900">Resources</h4>
              <ul className="mt-4 space-y-3">
                {["Blog", "Help Center", "API Documentation", "Status Page"].map((label) => (
                  <li key={label}>
                    <span className="text-sm text-slate-500 transition-colors hover:text-slate-900 cursor-pointer">
                      {label}
                    </span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Legal */}
            <div>
              <h4 className="text-sm font-semibold uppercase tracking-wider text-slate-900">Legal</h4>
              <ul className="mt-4 space-y-3">
                {["Privacy Policy", "Terms of Service", "Refund Policy", "RERA Compliance"].map((label) => (
                  <li key={label}>
                    <span className="text-sm text-slate-500 transition-colors hover:text-slate-900 cursor-pointer">
                      {label}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Bottom bar */}
          <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-slate-100 pt-8 sm:flex-row">
            <p className="text-sm text-slate-400">
              &copy; {new Date().getFullYear()} PropGenius AI. All rights reserved.
            </p>
            <p className="flex items-center gap-1.5 text-sm text-slate-400">
              Made with <Heart className="h-3.5 w-3.5 fill-red-500 text-red-500" /> in India
            </p>
            <div className="flex items-center gap-1.5 text-sm text-slate-400">
              <Zap className="h-3.5 w-3.5 text-primary-500" />
              Powered by Google Gemini AI
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
